# Generated by Django 3.2.18 on 2024-02-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='credentials',
            field=models.TextField(blank=True),
        ),
    ]
