# Generated by Django 3.2.18 on 2024-02-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_project_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
