# Generated by Django 3.2.18 on 2024-02-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20240229_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subscription',
        ),
    ]
