# Generated by Django 3.2.18 on 2024-02-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_remove_client_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.project')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.subscription')),
            ],
        ),
    ]
