# Generated by Django 3.2.18 on 2024-02-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_auto_20240229_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
