# Generated by Django 3.2.18 on 2024-02-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default_profile_photo.jpg', upload_to='profile_photos/'),
        ),
    ]
