# Generated by Django 3.2.18 on 2024-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0012_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionassignment',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionassignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
